vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        carousels:
            uri_prefix: /images/carousels
            upload_destination: '%kernel.project_dir%/public/images/carousels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        bookpages:
            uri_prefix: /images/bookpages
            upload_destination: '%kernel.project_dir%/public/images/bookpages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        books:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        authors:
            uri_prefix: /images/authors
            upload_destination: '%kernel.project_dir%/public/images/authors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer